language: python
python:
    - "2.7"

cache:
    directories:
        - $HOME/.cache

sudo: required

dist: trusty

compiler:
    - gcc

before_install:
    # Fix a travis/boto issue.  See
    # https://github.com/travis-ci/travis-ci/issues/7940
    - sudo rm -f /etc/boto.cfg

    - mkdir -p $HOME/.cache/node_modules || true
    - ln -sf $HOME/.cache/node_modules .
    - nvm install v8
    - npm install -g npm
    - npm install -g npm-install-retry
    - npm --version
    - npm prune

    - GIRDER_VERSION=2.x-maintenance
    - GIRDER_BUILD_PATH=$HOME/girder_build
    - main_path=$PWD
    - build_path=$PWD/build
    - mkdir -p $build_path

    - GIRDER_PATH=$build_path/girder
    - rm -rf $GIRDER_PATH
    - git clone https://github.com/girder/girder.git $GIRDER_PATH && git -C $GIRDER_PATH checkout $GIRDER_VERSION

    - ls -l $main_path
    - ln -sf $main_path $GIRDER_PATH/plugins/
    - ls -l $GIRDER_PATH/plugins
    - cd $GIRDER_PATH/plugins/AMI_plugin
    - ls -l
    - pwd
    - cd $GIRDER_PATH
    - pwd

    - export MONGO_VERSION=3.2.18
    - export PY_COVG="ON"
    - CACHE=$HOME/.cache source $GIRDER_PATH/scripts/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    - CACHE=$HOME/.cache CMAKE_VERSION=3.4.3 CMAKE_SHORT_VERSION=3.4 source $GIRDER_PATH/scripts/install_cmake.sh
    - cmake --version
install:
    - cd $GIRDER_PATH
    - pip install -U --upgrade-strategy eager -r requirements-dev.txt
    # - pip install -U --upgrade-strategy eager -e .[AMI_plugin]

    - npm-install-retry
    - BABEL_ENV=cover NYC_CWD="$main_path" girder-install web --plugins=AMI_plugin --dev

    - pip freeze  # report what we have installed
script:
    - mkdir -p $GIRDER_BUILD_PATH
    - cd $GIRDER_BUILD_PATH
    - cmake -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -DRUN_CORE_TESTS:BOOL="OFF" -DTEST_PLUGINS:STRING="AMI_plugin" $GIRDER_PATH
    - make -j 3
    - JASMINE_TIMEOUT=15000 ctest -VV

after_failure:
    # On failures, show the worker output and other information
    - pip freeze
    - cat /tmp/worker.out

after_success:
    - bash <(curl -s https://codecov.io/bash) -R $main_path -s $GIRDER_PATH